[tool.poetry]
name = 'blogproject'
version = '0.1.0'
description = ""
authors = ['yan <korotkevich3007@gmail.com>']
readme = 'README.md'

[tool.poetry.dependencies]
python = '^3.12'
requests = "^2.32.3"
aiogram = "^3.15.0"
python-dotenv = "^1.0.1"
